name : test-schedule
on :
  schedule:
    - cron : '*/5 * * * *'
jobs:
  cron-date-check:
    runs-on: ubuntu-latest
    steps:
      - name: Echo current time
        run : echo "Server time is $(date)"