name: conditional
on: [push]
jobs:
    if-condition-passed:
        if: ${{ contains(github.repository, 'gauravr397/Github-Examples') }}
        runs-on: ubuntu-latest
        steps:
            - name: See exactly what the variable contains
              run: echo "The repo name is ${{ github.repository }}"
            - name: "codition-check"
              run: echo "condition passed"
    
    codintion-skiped:
        runs-on: ubuntu-latest
        steps:
            - name: conditon-skipped
              run: echo "condition skiped running"
            - name: See exactly what the variable contains
              run: echo "The repo name is ${{ github.repository }}"