name : webhook-test
on:
    repository_dispatch:
        types:
            - webhook

jobs:
    respond-to-webhook:
        runs-on: ubuntu-latest
        steps:
            - name: Run Script
              run: echo "Event type - $GITHUB_EVENT_NAME"