name: workflow-cmd
on: [push]
jobs:
    myjob:
        runs-on: ubuntu-latest
        steps:
            - name: "grp logging"
              run : |
                echo "::group:: My grp msg"
                echo "msg1"
                echo "msg2"
                echo "msg3"                
                echo "::endgroup::"

            - name: "masking value"
              run: |
                echo "::add-mask::${{secrets.SECRET_VALUE}}"

            - name: "Fail workflow"
              run : |
                echo "::error:: My fail msg"
            
            - name: "Debug msg"
              run : |
                echo "::debug:: My debug msg"

            - name: Set environt variable
              run: |
                echo "ACTION_ENV=production" >> $GITHUB_ENV
                
            - name: Add dir to path
              run: |
                echo "/home/gr/Projects/Git-Actions/Github-Examples" >> $GITHUB_PATH
                
            - name: Set output var
              id: opt_step
              run: |
                echo "result=output_value" >> $GITHUB_OUTPUT

            - name: Use output var
              run: |
                echo "Ouput was ${{steps.opt_step.outputs.result}}"
            
            
                
